### ISSUE TITLE
ö or oe

### ISSUE THREAD

**Issue by fredhohman** [fredhohman/fredhohman.github.io#29]
For citation for Neo, @grtlr should the bibtex [on my site](https://github.com/fredhohman/fredhohman.github.io/blob/master/_posts/papers/2022-02-18-neo.md?plain=1#L38-L47)  be `goertler2022neo` or `gortler2022neo`? I want to align with https://github.com/apple/ml-hierarchical-confusion-matrix/pull/4

**Comment by grtlr** [comment]
`goertler` would be the correct one, but it's really not that important :)
